# -*- coding: utf-8 -*-
"""week3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lveDQ1T2XNknE5k7eXKk1ZA6iy28Z_-C
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from scipy import stats

# 2. Generate Synthetic Dataset
np.random.seed(42)

# Group A (Control): Mean purchase of $80, standard deviation of $15
group_a_purchases = np.random.normal(loc=80, scale=15, size=250)

# Group B (Treatment): Mean purchase of $83.5, standard deviation of $16
group_b_purchases = np.random.normal(loc=83.5, scale=16, size=250)

# Create a DataFrame
df = pd.DataFrame({
    'group': ['Group A'] * 250 + ['Group B'] * 250,
    'purchase_amount': np.concatenate([group_a_purchases, group_b_purchases])
})

display(df.head())
display(df.groupby('group').describe())

# 3. Visualize the Distributions
plt.figure(figsize=(10, 6))
sns.histplot(data=df, x='purchase_amount', hue='group', kde=True, bins=30, alpha=0.5)
plt.title('Distribution of Purchase Amounts by Group')
plt.xlabel('Purchase Amount ($)')
plt.ylabel('Frequency')
plt.grid(axis='y', linestyle='--', alpha=0.7)
plt.show()

t_stat, p_val = stats.ttest_ind(group_a_purchases, group_b_purchases, equal_var=False)

print(f"t-statistic: {t_stat:.4f}")
print(f"p-value: {p_val:.4f}")


alpha = 0.05
if p_val < alpha:
    print(f"\nReject the null hypothesis (p < {alpha}). There is a statistically significant difference in average order values between Group A and Group B.")
else:
    print(f"\nFail to reject the null hypothesis (p >= {alpha}). There is no statistically significant difference in average order values between Group A and Group B.")